
\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{DegTLNakLatex}[3/5/2015 custom nak class by Jan Hauke Maase edited by Hans Risser for the data experts gmbh]

\LoadClass{TLNakLatex}

\fancyhead[L]{\includegraphics[height=30pt]{image/data-experts-logo.png}\includegraphics[height=30pt]{image/transferleistung.jpg}} % Kopfzeile Links - Mitte
\fancyhead[R]{\includegraphics[height=30pt]{image/Nordakademie_Logo_klein.jpg}} % Kopfzeile rechts
